# Generated by Django 6.0.4 on 2026-09-24 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(db_index=True, help_text='Nombre descriptivo. Cuenta con índice en BD para búsquedas rápidas.', max_length=200, verbose_name='Título del Ítem')),
                ('categoria', models.CharField(db_index=True, help_text='Clasificación temática (ej. Tecnología, Documentación, Tutoriales).', max_length=100, verbose_name='Categoría')),
                ('descripcion', models.TextField(help_text='Detalle exhaustivo del contenido del ítem.', verbose_name='Descripción Completa')),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, help_text='Valor numérico con dos decimales.', max_digits=10, verbose_name='Precio / Costo')),
                ('disponible', models.BooleanField(db_index=True, default=True, help_text='Define si el ítem está visible para consultas y catálogo.', verbose_name='¿Disponible?')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'Ítem / Recurso',
                'verbose_name_plural': 'Ítems / Recursos',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['categoria', 'disponible'], name='idx_item_cat_disp'), models.Index(fields=['titulo'], name='idx_item_titulo')],
            },
        ),
    ]
