# Generated by Django 6.0.4 on 2026-09-24 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MensajeBienvenida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título descriptivo del mensaje', max_length=200, verbose_name='Título')),
                ('contenido', models.TextField(help_text='Texto completo del mensaje', verbose_name='Contenido')),
                ('activo', models.BooleanField(default=True, help_text='Indica si este mensaje debe mostrarse en la página principal', verbose_name='¿Está activo?')),
                ('creado_el', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('actualizado_el', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Mensaje de Bienvenida',
                'verbose_name_plural': 'Mensajes de Bienvenida',
                'ordering': ['-creado_el'],
            },
        ),
    ]
